<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.11.6 on win32)" generated="20231103 13:24:47.302" rpa="false" schemaversion="4">
<suite id="s1" name="Google Search Test" source="C:\Users\chris\OneDrive\Área de Trabalho\intelbras\develop\git\robot_tests\google-test\google_search_test.robot">
<test id="s1-t1" name="Cenário: Previsão do tempo em Florianópolis" line="5">
<kw name="Open browser">
<arg>chrome</arg>
<msg timestamp="20231103 13:24:47.328" level="FAIL">No keyword with name 'Open browser' found.</msg>
<status status="FAIL" starttime="20231103 13:24:47.328" endtime="20231103 13:24:47.328"/>
</kw>
<status status="FAIL" starttime="20231103 13:24:47.327" endtime="20231103 13:24:47.328">No keyword with name 'Open browser' found.</status>
</test>
<status status="FAIL" starttime="20231103 13:24:47.304" endtime="20231103 13:24:47.329"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Google Search Test">Google Search Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231103 13:24:47.324" level="ERROR">Error in file 'C:\Users\chris\OneDrive\Área de Trabalho\intelbras\develop\git\robot_tests\google-test\google_search_test.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\robot.exe
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\python311.zip
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\DLLs
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0
  C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\site-packages</msg>
</errors>
</robot>
